//currentstatus -> true means active
export let AddUserData=[
    {
        access : true,
        employeeid : "Krish",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : true,
        employeeid : "Krish Thakrar",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : false,
    },
    {
        access : true,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : false,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : false,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : true,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    },
    {
        access : false,
        employeeid : "Bold text column",
        employeename : "Regular text column",
        employeeemail : "Regular text column",
        contactno : "Regular text column",
        currentstatus : true,
    }
]